baseURL = "/"
languageCode = "en-us"
title = "Piped"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = 'Piped is a privacy friendly alternative YouTube frontend, which is efficient and scalable by design.'
  homepage_image = '/images/banner.webp'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Piped is a privacy friendly alternative YouTube frontend, which is efficient and scalable by design."
    meta_og_title = "Piped"
    meta_og_type = "website"
    meta_og_url = "https://piped-docs.kavin.rocks"
    meta_og_image = "https://avatars.githubusercontent.com/u/74294114?s=250"
    meta_og_description = "Piped is a privacy friendly alternative YouTube frontend, which is efficient and scalable by design."
    meta_twitter_card = "summary"
    meta_twitter_site = ""
    meta_twitter_creator = ""

  [params.logo]
      mobile = "/images/logo.svg"
      standard  = "/images/logo.svg"
