name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          extended: true
      - run: hugo --minify
      - uses: aquiladev/ipfs-action@v0.1.5
        id: ipfs-add
        with:
          path: ./public
          service: infura
      - name: Update DNSLink
        run: npx dnslink-cloudflare -d kavin.rocks -l /ipfs/${{ steps.ipfs-add.outputs.hash }} -r _dnslink.piped-docs
        env:
          CF_API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
